src/ipc/client.rs
src/ipc/platform/mod.rs
src/ipc/platform/unix_connection.rs

Add support for unix platform

---

src/ipc/client.rs
src/ipc/platform/unix_connection.rs
src/ipc/platform/windows_connection.rs

Fix connection issues

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs

Add custom buttons

---

README.md
lua/cord.lua
src/ipc/platform/unix_connection.rs
src/json/serialize.rs
src/lib.rs

Fix user commands

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs

Allow swapping the positions of the fields

---

README.md
lua/cord.lua
lua/cord/utils.lua

Add workspace blacklist

---

README.md
lua/cord.lua

Add user commands for managing the idle status

---

lua/cord.lua
lua/cord/utils.lua
src/lib.rs
src/utils.rs

perf: move crucial components to the Rust codebase

---

README.md
lua/cord.lua

Includes breaking changes to the configuration:
```diff
idle = {
-   show_idle = true,    -- Enable idle status
+   enable = true,       -- Enable idle status
+   show_status = true,  -- Display idle status, disable to hide the rich presence on idle
},
```
Closes #36

feat!: Provide a configuration option to disable rich presence on idle

---

src/ipc/platform/unix_connection.rs

feat: add support for Flatpak and Snap IPC paths

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs

feat: Add a user command for changing the workspace name

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs
src/util/mod.rs
src/util/status.rs

Fix `workspace_blacklist`

---

lua/cord.lua

feat: Support executables launched using `toggleterm.nvim`

---

lua/cord.lua

fix: Issues with displaying the idle status

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs
src/util/utils.rs

feat: Implement `swap_icons`

---

build

Improve build script compatibility

---

lua/cord.lua
lua/cord/log.lua
lua/cord/utils.lua
src/ipc/client.rs
src/ipc/platform/unix_connection.rs
src/ipc/platform/windows_connection.rs
src/lib.rs
src/util/status.rs

feat: Improve error handling

---

lua/cord.lua
lua/cord/log.lua

feat: Add `config.log_level`

---

lua/cord/log.lua

fix: `log_level` failing when set to nil

---

lua/cord.lua
lua/cord/utils.lua
src/lib.rs
src/mappings/mod.rs

feat: Provide an option to override all icons with a custom one

---

README.md
lua/cord.lua

refactor: Set `idle.disable_on_focus` to `false` by default

---

src/json/mod.rs
src/json/serialize.rs
src/json/utils.rs

fix: Escape special characters in the JSON

---

src/mappings/file_browser.rs

feat: Add Yazi as a file explorer

---

lua/cord.lua

addresses #119. see [this](https://github.com/vyfor/cord.nvim/issues/119#issuecomment-2478371390) comment.

fix: Replace `os.clock()` with `vim.loop.hrtime()`

---

lua/cord.lua

feat: Use current file's directory as the workspace instead of cwd

---

lua/cord.lua

fix: `config.reset_on_idle`

---

.gitignore
build.bat

lol windows fix
- added .dll cause windows wants it that way
- updated .gitignore for windows
was trying to use this on windows and it didn't work so here's the fix 😅

Windows fix

---

README.md
lua/cord.lua
lua/cord/utils.lua
src/lib.rs

feat: Add a configuration option to replace the default idle icon

---

lua/cord/api/usercmd.lua
lua/cord/server/init.lua
plugin/cord.vim

feat(usercmds): Add `:Cord status`

---

lua/cord/plugin/config/init.lua
lua/cord/server/event/receiver.lua
lua/cord/server/init.lua
lua/cord/server/spawn/init.lua
lua/cord/server/update/init.lua
src/cli/args.rs
src/cord.rs
src/ipc/discord/client.rs
src/ipc/discord/platform/unix.rs
src/ipc/discord/platform/windows.rs
src/main.rs
src/messages/events/client/clear_activity.rs
src/messages/events/client/connect.rs
src/messages/events/client/disconnect.rs
src/messages/events/client/update_activity.rs
src/messages/events/local/error.rs
src/messages/events/server/disconnect.rs
src/messages/events/server/mod.rs

feat: Implement reconnection mechanism for Discord

---

lua/cord/plugin/activity/mappings.lua

added dashboard support for NvDash for neocord

feat: add dashboard support for NvDash

---

lua/cord/plugin/activity/init.lua
lua/cord/plugin/activity/mappings.lua
lua/cord/plugin/config/init.lua

feat: More mappings

---

.github/wiki/Configuration.md
.github/wiki/Examples.md
lua/cord/plugin/activity/init.lua
lua/cord/plugin/activity/manager.lua
lua/cord/plugin/config/init.lua

feat(manager): allow disabling text categories via boolean values

---

.github/wiki/Configuration.md
lua/cord/plugin/config/init.lua
lua/cord/server/init.lua
lua/cord/server/spawn/init.lua
src/cli/args.rs
src/cord.rs
src/ipc/discord/client.rs
src/ipc/discord/platform/unix.rs
src/ipc/discord/platform/windows.rs
src/main.rs
src/messages/events/local/error.rs

feat: Implement initial reconnection logic

---

.github/wiki/Configuration.md
.github/wiki/Examples.md
.github/wiki/Home.md
.github/wiki/Plugin-System.md
.github/wiki/Plugins.md
README.md
lua/cord/api/plugin.lua
lua/cord/api/usercmd.lua
lua/cord/plugin/activity/hooks.lua
lua/cord/plugin/activity/init.lua
lua/cord/plugin/activity/manager.lua
lua/cord/plugin/activity/mappings.lua
lua/cord/plugin/config/init.lua
lua/cord/plugin/config/util.lua
lua/cord/plugins/diagnostics.lua
lua/cord/plugins/local_time.lua
lua/cord/plugins/scoped_timestamps.lua
lua/cord/server/init.lua

addresses #171 
closes #172 
closes #173

feat: Introduce plugins system

---

plugin/cord.vim

feat: notify users on deprecated branch

---

lua/cord/plugin/activity/manager.lua
lua/cord/plugin/fs/workspace.lua

feat(fs): implement protocol-based workspace parsing

---

lua/cord/plugin/activity/mappings.lua

feat: add mail-related filetypes

---

.github/wiki/Configuration.md
README.md
lua/cord/api/icon.lua
lua/cord/plugin/config/init.lua

feat(icons): add `catppuccin` and `material` icon themes

---

lua/cord/plugin/fs/workspace.lua

fix(fs): correctly identify workspace name

---

.github/wiki/Contributing.md
.github/wiki/FAQ.md
.github/wiki/Troubleshooting.md
plugin/cord.vim

docs: improve documentation and contribution guidelines

---

.github/wiki/Configuration.md

docs : update Configuration.md

docs: update icon.get function signature

---

.github/wiki/Configuration.md
lua/cord/api/config.lua
lua/cord/plugin/config/init.lua
lua/cord/plugin/config/util.lua

feat(config): add `text.default` option

---

lua/cord/plugin/activity/mappings.lua

feat(mappings): add `jule` filetype

---

.github/wiki/Configuration.md
lua/cord/api/config.lua
lua/cord/plugin/config/init.lua
lua/cord/plugin/fs/workspace.lua

feat(workspace): custom root markers

---

.github/wiki/Configuration.md
lua/cord/api/config.lua
lua/cord/plugin/config/init.lua
lua/cord/plugin/fs/workspace.lua

feat(workspace): allow limiting the scope of upward traversal to cwd

---

lua/cord/api/plugin.lua

fix(plugins): fix `plugins` table's length check

---

lua/cord/plugins/local_time.lua
lua/cord/plugins/scoped_timestamps.lua

feat(plugins): implement config validation for scoped timestamps & local time plugins

---

.github/wiki/Configuration.md
lua/cord.lua
plugin/cord.vim

feat: add support for manual plugin startup

---

.github/wiki/Configuration.md
lua/cord/plugin/activity/manager.lua
src/presence/activity.rs

feat(activity): add support for the new fields in the `Activity` object

---

lua/cord/plugins/diagnostics.lua

When there is only one problem, we still get a message like `- 1 problems` instead of `- 1 problem`.
This simply fixes that.

fix(plugins.diagnostics): - support 1 problem(!) scenario

---

.github/wiki/Plugins.md
lua/cord/core/uv/fs.lua
lua/cord/plugin/activity/manager.lua
lua/cord/plugins/persistent_timer.lua

feat(plugins): add `PersistentTimer` plugin

---

README.md

docs(readme): add `vim.pack` installation instructions

---

.github/wiki/Configuration.md
lua/cord/api/config.lua
lua/cord/plugin/config/init.lua
lua/cord/server/event/sender.lua
lua/cord/server/init.lua
src/cord.rs
src/ipc/discord/client.rs
src/ipc/discord/platform/unix.rs
src/ipc/discord/platform/windows.rs
src/messages/events/client/connect.rs
src/messages/events/client/initialize.rs
src/messages/events/local/error.rs
src/types/config.rs
src/util/logger.rs

Add support for custom Discord IPC paths

---

src/ipc/discord/client.rs

fix(ipc): include Flatpak and Snap Discord installations in the default path list

---

lua/cord/internal/hooks.lua

fix(hooks): log errors caught during hooks' callback execution

---

lua/cord/api/command.lua
lua/cord/server/init.lua
lua/cord/server/ipc/sender.lua
src/messages/events/client/mod.rs
src/messages/events/client/restart.rs

fix: make `:Cord restart` reconnect all Neovim instances

---

lua/cord/server/init.lua

fix: prevent redundant reinitialization on multiple ready events

---

.github/wiki/Examples.md
.github/wiki/Plugins.md
lua/cord/api/config/init.lua
lua/cord/internal/manager.lua
lua/cord/plugins/visibility.lua

closes #305
- **fix(manager): update `is_paused` flag early on**
- **feat(plugins): add `Visibility` plugin**

feat(plugins): add `Visibility` plugin

---

lua/cord/internal/activity/mappings.lua

feat(mappings): add `just` filetype
